export const marketArr = [
	{
		id: 'ma01',
		title: 'Volunteer forever',
		about: 'Volunteer Forever was built as a way to break down those barriers: it’s a comprehensive online resource that helps people all over the world find and fund their best volunteer, intern and teach abroad experiences. Our goal is to provide expert information and expert resources that will empower you to travel and do good!',
		location: 'Colombo',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/turtleConservation.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
	{
		id: 'ma02',
		title: 'International Volunteer HQ,',
		about: 'At International Volunteer HQ, we bring people of more than 96 nationalities together to create positive transformation through regenerative travel. This transformation takes place not just within the communities we support, but also within volunteers themselves.',
		location: 'Galle',
		price: '$$$$$$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/kindergarten & Teaching.jpg',
			alt: 'Events Cards',
		},
		status: 'Featured',
	},
	{
		id: 'ma03',
		title: 'Rotary Colombo',
		about: 'We the officers of Rotary Club of Colombo, Ceylon, do hereby certify that this list constitutes the charter membership list and agreements of the Rotary Club of Colombo, Ceylon.',
		location: 'Colombo',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/org/Rotary.jpg',
			alt: 'Events Cards',
		},
		status: 'Latest',
	},
	{
		id: 'ma04',
		title: 'Lions Clubs',
		about: 'Our association is made up of 1.4 million members in 49,000 clubs who bring hands and hearts to the communities we serve in nearly every country on earth. Our Lions and Leos help hundreds of millions of people every year. Check out the ways we serve.',
		location: 'Colombo',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/wildElephannt.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
	{
		id: 'ma05',
		title: 'United Nations Volunteers',
		about: 'UNV is based in Bonn, Germany, with around 150 staff members at headquarters, and 12,408 UN Volunteers deployed in the field in 2022. UNV has an office in New York, six regional offices in Amman, Bangkok, Dakar, Istanbul, Nairobi and Panama City, a liaison office in Tokyo and around 60 Field Units. Toily Kurbanov is our Executive Coordinator.',
		location: 'Colombo',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/org/unvol.png',
			alt: 'Events Cards',
		},
		status: 'Latest',
	},
	{
		id: 'ma06',
		title: 'AIESEC',
		about: 'AIESEC is a community of young people, passionately driven by one cause: peace and fulfilment of humankind’s potential.',
		location: 'Colombo',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/pre Medical .jpg',
			alt: 'Events Cards',
		},
		status: 'Featured',
	},
	{
		id: 'ma06',
		title: 'Test test test ',
		about: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Id officiis unde cupiditate cum natus? Tempore obcaecati odio cum corporis repellat qui sed consequatur velit ullam veritatis laborum ut, vitae consequuntur',
		location: 'Colombo',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '',
			alt: 'Events Cards',
		},
		status: 'Featured',
	},
];
