export const marketArr = [
	{
		id: 'ma01',
		title: 'Sea Turtle Conservation Volunteering in Sri Lanka',
		location: 'Galle',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/turtleConservation.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
	{
		id: 'ma02',
		title: '1 Week Special Volunteer Program in Sri Lanka',
		location: 'Galle',
		price: '$$$$$$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/kindergarten & Teaching.jpg',
			alt: 'Events Cards',
		},
		status: 'Featured',
	},
	{
		id: 'ma03',
		title: 'Volunteer in a Dog Care Project',
		location: 'Gampaha',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/dog_care.jpg',
			alt: 'Events Cards',
		},
		status: 'Latest',
	},
	{
		id: 'ma04',
		title: 'Wild Elephant Conservation & Research Program',
		location: 'Wasgamuwa National Park',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/wildElephannt.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
	{
		id: 'ma05',
		title: 'Turtle Conservation and Exploring Sri Lanka',
		location: 'Galle',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/turtle.jpg',
			alt: 'Events Cards',
		},
		status: 'Latest',
	},
	{
		id: 'ma06',
		title: 'Medical Internship in Sri Lanka',
		location: 'Kandy',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/pre Medical .jpg',
			alt: 'Events Cards',
		},
		status: 'Featured',
	},
	{
		id: 'ma07',
		title: 'Nursing Internship in Sri Lanka',
		location: 'Mathale',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/nursing Internship.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
	{
		id: 'ma08',
		title: 'Volunteer for Women Empowerment Program',
		location: 'Galle',
		price: '$$$$$$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/women.jpg',
			alt: 'Events Cards',
		},
		status: 'Latest',
	},
	{
		id: 'ma09',
		title: 'Environmental Conservation Project',
		location: 'Matara',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/environmentalConservation.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
	{
		id: 'ma10',
		title: 'Childrens Teaching Volunteer Program',
		location: 'Town Hall',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/children.jpg',
			alt: 'Events Cards',
		},
		status: 'Featured',
	},
	{
		id: 'ma11',
		title: 'Kindergarten & Teaching Volunteer Program',
		location: 'Maharagama',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/kindergarten & Teaching.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
	{
		id: 'ma12',
		title: 'Pre Medical & Nursing Healthcare Volunteer Program Sri Lanka',
		location: 'Maharagama',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/medical Internship.jpg',
			alt: 'Events Cards',
		},
		status: 'Featured',
	},
	{
		id: 'ma13',
		title: 'Beach Clean Up',
		location: 'Maharagama',
		price: '$$$',
		date: '23.04.2024',
		img: {
			src: '/img/Volunteer/beach.jpg',
			alt: 'Events Cards',
		},
		status: 'Urgent',
	},
];
